"use client"

import Link from "next/link"
import Image from "next/image"
import { ArrowLeft, ArrowRight, ExternalLink, ChevronRight } from "lucide-react"
import { motion } from "framer-motion"
import { BackgroundPaths } from "@/components/ui/background-paths"

export default function RegimeDetectionPage() {
  const fadeUpVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: (i: number) => ({
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.8,
        delay: 0.2 + i * 0.1,
        ease: [0.25, 0.4, 0.25, 1],
      },
    }),
  }

  const techStack = [
    "Python",
    "pandas",
    "NumPy",
    "statsmodels",
    "yfinance",
    "FRED",
    "Backtesting",
    "Hidden Markov Models",
  ]

  const tldrPoints = [
    "Estimated a 4-state Hidden Markov / regime-switching model on US industrial production and CPI to infer latent business-cycle regimes (Crisis, Stagnation, Expansion, Boom) from 1971 onwards.",
    'Used smoothed regime probabilities to study the structure of the cycle (average growth, inflation and asset behaviour in each state), and filtered probabilities for "real-time" trading signals to avoid look-ahead bias.',
    "Mapped regimes into an intuitive macro playbook: long duration and gold in Crisis, tilt to credit and quality equities in Stagnation, hold a balanced equity-bond mix in Expansion, and rotate into cyclicals and commodities in Boom.",
    "Aligned monthly macro regimes with ETF returns for SPY, TLT, HYG, DBC and GLD, then computed regime-conditional Sharpe ratios and pairwise correlations to see how diversification changes across the cycle.",
    "Ran a one-month-lagged, real-time backtest from 2007–2025 and beat an equal-weight benchmark: total return 349% vs 220%, Sharpe 0.88 vs 0.74, and shallower max drawdown (-15.9% vs -24.4%).",
  ]

  const demonstratesPoints = [
    "Building and interpreting regime-switching models. Estimated a Markov-switching growth model in Python (statsmodels) with regime-specific means and variances, selected the number of states via BIC, and distinguished between smoothed and filtered probabilities for analysis vs trading.",
    'Translating macro regimes into actual portfolio rules. Turned abstract "Crisis / Boom / Stagnation / Expansion" labels into concrete allocations across equities, duration, credit and commodities, based on regime-level Sharpe and correlation patterns.',
    "Handling real-world backtesting issues. Carefully aligned macro and market data at a monthly frequency, lagged signals to avoid look-ahead, and separated the long macro history used to learn regimes from the shorter ETF history used for portfolio testing.",
    "Explaining where alpha comes from. Per-regime attribution tables show that most of the excess return is generated by tilting towards defensive assets in Crises and Stagnation and towards commodities and cyclicals in Booms, while correlation analysis documents how stock–bond and stock–commodity relationships flip sign across regimes.",
    "Communicating research like a quant PM. Produced a full research pipeline—from FRED/Yahoo data ingestion, feature engineering and HMM estimation through to portfolio construction, backtesting and risk diagnostics—and packaged it in a way that a PM can challenge, modify, or plug into a broader asset-allocation process.",
  ]

  const pipelineSteps = [
    "FRED & Yahoo Finance",
    "Growth & Inflation series",
    "HMM estimation (4 states)",
    "Regime probabilities",
    "Asset allocation rules",
    "Backtest & evaluation",
  ]

  const figures = [
    {
      src: "/images/regime-probabilities.png",
      caption:
        "Figure 1: Historical Regime Probabilities (Smoothed). Extended periods of Expansion and shorter but intense episodes of Crisis and Boom appear clearly. Historical episodes like the 1970s, early 1980s double-dip recession, the 2008 global financial crisis, the 2020 Covid shock, and the 2021–2022 inflation episode correspond to intuitive shifts in the regime probabilities.",
      alt: "Historical regime probabilities chart showing 4 regimes over time from 1975 to 2020",
    },
    {
      src: "/images/growth-inflation-scatter.png",
      caption:
        "Figure 2: Growth vs Inflation scatter plot colored by ordered regime. The points cluster into distinct clouds. One in the bottom area (negative growth), another around zero growth, and two higher-growth clusters, each with different inflation levels. This visually confirms that the HMM has discovered meaningful macro clusters in the Growth–Inflation plane, rather than arbitrary states.",
      alt: "Scatter plot of Growth YoY vs Inflation YoY colored by 4 regimes showing distinct clusters",
    },
    {
      src: "/images/regime-performance-table.png",
      caption:
        "Figure 3: Performance decomposition by macro regime. For each regime, the months classified into that state (using the real-time filtered signal) are isolated, and annualised returns and Sharpe ratios are computed for both the Regime Strategy and the Equal-Weight Benchmark.",
      alt: "Table showing regime-specific performance metrics including returns, alpha, and Sharpe ratios",
    },
    {
      src: "/images/regime-backtest-performance.png",
      caption:
        "Figure 4: Cumulative performance of the Macro Regime Model vs Benchmark. Over the 2007–2025 test window, the regime strategy grows $1 into roughly $4.5, versus about $3.2 for the benchmark, corresponding to a total return of 349% vs 220%. This outperformance comes with only a slightly higher annualised volatility (9.9% vs 9.2%), so the Sharpe ratio improves from 0.74 to 0.88. The maximum drawdown is also smaller (–15.9% vs –24.4%), meaning the macro-aware allocation not only compounds faster but also experiences shallower peak-to-trough losses.",
      alt: "Line chart showing cumulative performance comparison between Regime Macro Strategy and Equal Weight Benchmark from 2008 to 2026",
    },
  ]

  return (
    <main className="relative min-h-screen w-full overflow-hidden bg-[#030303]">
      <BackgroundPaths />

      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-blue-500/[0.05] via-transparent to-indigo-500/[0.05] blur-3xl" />

      <div className="relative z-10 mx-auto max-w-5xl px-4 py-12 md:px-8 md:py-16">
        {/* Back button */}
        <motion.div custom={0} variants={fadeUpVariants} initial="hidden" animate="visible">
          <Link
            href="/projects"
            className="inline-flex items-center gap-2 text-white/50 hover:text-blue-400 transition-colors mb-10"
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm">Back to Projects</span>
          </Link>
        </motion.div>

        <header className="mb-16">
          <motion.h1
            custom={1}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
            className="text-4xl md:text-5xl lg:text-6xl font-serif text-white mb-6 tracking-[-0.02em] leading-[1.1]"
          >
            Macro Regime Model for{" "}
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-blue-500">
              Multi-Asset Allocation
            </span>
          </motion.h1>

          <motion.p
            custom={2}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
            className="text-lg md:text-xl text-white/60 mb-8 leading-relaxed max-w-3xl"
          >
            End-to-end regime-switching model that learns 4 macro regimes from US growth and inflation, then allocates
            across equities, bonds, credit and commodities to test whether a small macro dashboard can systematically
            improve portfolio returns.
          </motion.p>

          {/* Headline metrics strip */}
          <motion.div
            custom={2.5}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
            className="flex flex-wrap gap-6 text-sm text-white/50 mb-8"
          >
            <span>
              <span className="text-white/70 font-medium">OOS:</span> Jul 2007 – Sep 2025
            </span>
            <span>
              <span className="text-white/70 font-medium">Style:</span> Regime-based multi-asset rotation
            </span>
            <span>
              <span className="text-white/70 font-medium">Sharpe:</span> 0.88 vs 0.74
            </span>
            <span>
              <span className="text-white/70 font-medium">Data:</span> FRED, Yahoo Finance
            </span>
          </motion.div>

          {/* CTA buttons */}
          <motion.div
            custom={3}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
            className="flex flex-wrap gap-4 mb-10"
          >
            <a
              href="https://johoblogs.medium.com/project-macro-growth-inflation-regime-model-d9622b9dba15"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg transition-colors"
            >
              Read Article
              <ExternalLink className="w-4 h-4" />
            </a>
            <a
              href="https://github.com/oj0nathan/Macro_Regime_Switching_Model"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 text-white/80 font-medium rounded-lg border border-white/10 transition-colors"
            >
              View Code
              <ExternalLink className="w-4 h-4" />
            </a>
          </motion.div>

          {/* Tech stack */}
          <motion.div custom={4} variants={fadeUpVariants} initial="hidden" animate="visible">
            <div className="flex flex-wrap gap-2">
              {techStack.map((tech) => (
                <span
                  key={tech}
                  className="px-3 py-1.5 text-xs text-white/60 font-mono bg-white/5 border border-white/10 rounded-full"
                >
                  {tech}
                </span>
              ))}
            </div>
          </motion.div>
        </header>

        {/* TL;DR Section */}
        <motion.section custom={5} variants={fadeUpVariants} initial="hidden" animate="visible" className="mb-16">
          <h2 className="text-2xl md:text-3xl font-serif text-white mb-2 tracking-[-0.01em]">TL;DR</h2>
          <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-transparent mb-8" />
          <ul className="space-y-5">
            {tldrPoints.map((point, index) => (
              <li key={index} className="flex gap-4 text-white/70 text-base md:text-lg leading-relaxed">
                <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </motion.section>

        {/* What this project demonstrates */}
        <motion.section custom={6} variants={fadeUpVariants} initial="hidden" animate="visible" className="mb-16">
          <h2 className="text-2xl md:text-3xl font-serif text-white mb-2 tracking-[-0.01em]">
            What this project demonstrates
          </h2>
          <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-transparent mb-8" />
          <ul className="space-y-5">
            {demonstratesPoints.map((point, index) => (
              <li key={index} className="flex gap-4 text-white/70 text-base md:text-lg leading-relaxed">
                <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </motion.section>

        {/* Pipeline */}
        <motion.section custom={6.5} variants={fadeUpVariants} initial="hidden" animate="visible" className="mb-16">
          <h2 className="text-2xl md:text-3xl font-serif text-white mb-2 tracking-[-0.01em]">Pipeline</h2>
          <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-transparent mb-8" />
          <div className="flex flex-wrap items-center justify-center gap-2 md:gap-3">
            {pipelineSteps.map((step, index) => (
              <div key={step} className="flex items-center gap-2 md:gap-3">
                <span className="px-4 py-2 text-xs md:text-sm text-white/80 font-mono bg-white/5 border border-white/10 rounded-full whitespace-nowrap">
                  {step}
                </span>
                {index < pipelineSteps.length - 1 && (
                  <ChevronRight className="w-4 h-4 text-blue-400 flex-shrink-0 hidden sm:block" />
                )}
              </div>
            ))}
          </div>
        </motion.section>

        {/* Key Visuals */}
        <motion.section custom={7} variants={fadeUpVariants} initial="hidden" animate="visible" className="mb-16">
          <h2 className="text-2xl md:text-3xl font-serif text-white mb-2 tracking-[-0.01em]">Key Visuals</h2>
          <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-transparent mb-8" />
          <div className="space-y-12">
            {figures.map((figure, index) => (
              <div key={index} className="max-w-4xl mx-auto">
                <div className="relative aspect-video overflow-hidden rounded-xl border border-white/10 bg-white shadow-lg shadow-black/20">
                  <Image src={figure.src || "/placeholder.svg"} alt={figure.alt} fill className="object-contain" />
                </div>
                <p className="mt-4 text-sm text-white/50 leading-relaxed italic text-left">{figure.caption}</p>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Appendix: What is a Hidden Markov Model? */}
        <motion.section custom={8} variants={fadeUpVariants} initial="hidden" animate="visible" className="mb-16">
          <h2 className="text-2xl md:text-3xl font-serif text-white mb-2 tracking-[-0.01em]">
            Appendix: What is a Hidden Markov Model?
          </h2>
          <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-transparent mb-10" />

          <div className="space-y-8 text-white/70">
            <div className="space-y-4">
              <h3 className="text-lg md:text-xl font-semibold text-white tracking-[-0.01em]">The Core Idea</h3>
              <p className="text-base md:text-lg leading-relaxed">
                A Hidden Markov Model (HMM) is a statistical model for systems that move between a small number of
                <em className="text-white/90"> hidden states</em> over time, while we only observe noisy signals
                generated by those states.
              </p>
              <p className="text-base md:text-lg leading-relaxed">
                The <strong className="text-white/90">"Markov"</strong> part means the future state depends only on the
                current state (not the full history), and the <strong className="text-white/90">"hidden"</strong> part
                means we never observe the state directly.
              </p>
            </div>

            <div className="space-y-4">
              <h3 className="text-lg md:text-xl font-semibold text-white tracking-[-0.01em]">How It Works</h3>
              <p className="text-base md:text-lg leading-relaxed">For each state, the model specifies:</p>
              <ul className="space-y-3 ml-4">
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">1.</span>
                  <span>
                    <strong className="text-white/90">Emission distribution:</strong> A probability distribution for the
                    observed data (for example, a normal distribution with a state-specific mean and volatility).
                  </span>
                </li>
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">2.</span>
                  <span>
                    <strong className="text-white/90">Transition matrix:</strong> The probability of moving from one
                    state to another at each step.
                  </span>
                </li>
              </ul>
            </div>

            <div className="space-y-4">
              <h3 className="text-lg md:text-xl font-semibold text-white tracking-[-0.01em]">
                Inference: What the Model Learns
              </h3>
              <p className="text-base md:text-lg leading-relaxed">
                Given a time series of observations, an HMM uses algorithms like{" "}
                <em className="text-white/90">forward–backward</em> to infer two things:
              </p>
              <ul className="space-y-3 ml-4">
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                  <span>
                    The <strong className="text-white/90">probability of being in each state</strong> at every point in
                    time
                  </span>
                </li>
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                  <span>
                    The <strong className="text-white/90">most likely sequence of states</strong> that generated the
                    data
                  </span>
                </li>
              </ul>
            </div>

            <div className="flex justify-center my-10">
              <div className="bg-white rounded-xl p-6 max-w-xl w-full">
                <img
                  src="/images/hmm-diagram.png"
                  alt="Hidden Markov Model diagram showing hidden states X1, X2, X3 connected by transition probabilities (red arrows) and observations Y1, Y2, Y3 connected by emission probabilities (blue arrows)"
                  className="w-full h-auto"
                />
              </div>
            </div>

            <div className="space-y-4">
              <h3 className="text-lg md:text-xl font-semibold text-white tracking-[-0.01em]">Applications</h3>
              <p className="text-base md:text-lg leading-relaxed">
                HMMs are useful whenever you believe there are unobserved regimes driving what you see:
              </p>
              <ul className="space-y-3 ml-4">
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                  <span>
                    <strong className="text-white/90">Speech recognition:</strong> Hidden phonemes generate observed
                    audio signals
                  </span>
                </li>
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                  <span>
                    <strong className="text-white/90">Fault detection:</strong> Hidden machine states generate sensor
                    readings
                  </span>
                </li>
                <li className="flex gap-4 text-base md:text-lg leading-relaxed">
                  <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                  <span>
                    <strong className="text-white/90">Financial markets:</strong> Hidden "economic regimes" (Crisis,
                    Expansion, Boom, Stagnation) influence observable returns and volatility
                  </span>
                </li>
              </ul>
            </div>

            <div className="bg-white/5 border border-white/10 rounded-xl p-6 mt-8">
              <p className="text-base md:text-lg leading-relaxed italic text-white/60">
                In this project, we use an HMM to infer 4 latent macro regimes from US growth (industrial production)
                and inflation (CPI) data, then use these regime probabilities to drive asset allocation decisions across
                equities, bonds, credit, and commodities.
              </p>
            </div>
          </div>
        </motion.section>

        {/* Bottom CTAs */}
        <motion.section
          custom={9}
          variants={fadeUpVariants}
          initial="hidden"
          animate="visible"
          className="pt-10 border-t border-white/10"
        >
          <div className="flex flex-col sm:flex-row gap-4">
            <a
              href="https://johoblogs.medium.com/project-macro-growth-inflation-regime-model-d9622b9dba15"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 transition-colors font-medium"
            >
              Read the full case study on Medium
              <ArrowRight className="w-4 h-4" />
            </a>
            <a
              href="https://github.com/oj0nathan/Macro_Regime_Switching_Model"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 transition-colors font-medium"
            >
              Browse the code on GitHub
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>
        </motion.section>
      </div>

      {/* Bottom gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-t from-[#030303] via-transparent to-[#030303]/80 pointer-events-none" />
    </main>
  )
}
